import Head from 'next/head';
import { Box, Button, styled } from '@mui/material';

const StyledWrapper = styled(Box)`
  margin: 0 auto;
  gap: 20px;
  display: flex;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>RuMate</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <StyledWrapper>
        <Button variant='contained'>Iniciar sesion</Button>
        <Button variant='outlined'>Registrate</Button>
      </StyledWrapper>
    </>
  );
}
